FROM --platform=linux/amd64 ubuntu:20.04 as builder

RUN apt-get update
RUN DEBIAN_FRONTEND=noninteractive apt-get install -y build-essential clang

COPY . /repo
WORKDIR /repo/src
RUN make -j8
RUN make install
WORKDIR /repo/src/fuzz
RUN make -j8

FROM ubuntu:20.04 as package
COPY --from=builder /repo/src/fuzz/cmd /
